### ISSUE TITLE
Macktrucks MX  Site consolidated issues 

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-macktrucks-com-mx#14]
**Content Issues:**
Home page :
- [x] 1. Logo image overlaps the menu labels in case of responsive short width screen - **FIXED**
- [x] 2.  Header Navigation:             -  **Kannan Confirmed it as Intentional changes for MX so FIXED**
           Características sub menu missing from Camiones menu
           Motores sub menu missing from Teen Motriz menu 
           Clicking on Compra Mack Menu shows page can’t be displayed (https://www.macktrucks.com.mx/buy-mack/)
           Repuestos sub menu missing from  ‘Repuestos y Servicios’
- [ ] 3. Clicking on MAS INFORMACION  button  displays page can’t be displayed 
- [x] 4. Footer has incorrect number of icons ( X, Instagram not authored ) & missing multiple links 
- [x] 5. Extra White space displayed above footer 
- [x] 6. Header Menu is not like redesigned header menu : **FIXED**
- [x] 7. https://www.macktrucks.com.mx/powertrain-and-suspensions/  page has hero image with unreadable text :

- [x] 8. Mack Anthem font size is not in sync with other truck titles.

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/c60f4d8d-fc74-449b-ab6b-51b749c9d77e">

- [x] 9. Truck names does not have Registered trademarks :
![image](https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/b0cdec2c-7d5d-4752-9be5-e40de603be82)

- [x] 10  Page does not exist : https://www.macktrucks.com.mx/buy-mack/  
- [x] 11 : https://www.macktrucks.com.mx/powertrain-and-suspensions/  Font text is not as expected 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/c61254c3-9156-4b72-b7b0-17ff6781c184">

- [ ] 12 Query:  Clicking on MAS INFORMACION  button shows  https://www.macktrucks.com.mx/NASCAR  page with Page cant be displayed in English language so is it required in native language of site?

- [ ] 13 Footer :  [Noticias Mack] ~[Contáctanos]~ links are not configured
- [ ] 14.  Email text box and enter arrow icon are not displayed although all cookies are accepted   
"Mantente en contacto con Mack"

- [x] 15. Header Menu :  Pages showing 404
**Experiencia** :
[Comprar Mack](https://www.macktrucks.com.mx/buy-mack/)
[Solicite un presupuesto](https://www.macktrucks.com.mx/buy-mack/request-a-quote/)
~[Eventos](https://www.macktrucks.com.mx/trucks/events/)~  [GD] Eventos link is not present with new content

- [x]  **Repuestos y servicios >> REPUESTOS >>** :
[PartsASIST](https://www.macktrucks.com.mx/parts-and-services/parts/partsasist/)

- [x] **Repuestos y servicios>> SOPORTE >>** :
[Preguntas frecuentes](https://www.macktrucks.com.mx/parts-and-services/support/faqs/)
[Manuales y recursos](https://www.macktrucks.com.mx/parts-and-services/support/manuals-and-resources/)
[Garantía](https://www.macktrucks.com.mx/parts-and-services/support/warranty/)

- [x] 16. https://www.macktrucks.com.mx/about-mack/careers/  Hero image & text is missing 

- [x] 17. https://www.macktrucks.com.mx/about-mack/facilities/ Hero image & text is missing
- [x]  18. https://www.macktrucks.com.mx/trucks/anthem/  has carousal container with no background set and incorrect font and alignment of text: 
![image](https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/d9d4bea9-1306-4be8-a6b3-d3a8c3cb054c) 
Carousal images are small than that of macktrucks.com

- [x] 19. https://www.macktrucks.com.mx/trucks/anthem/    Sub nav block is not displayed
![image](https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/83fa2070-e9ba-433c-baf1-10c66cd4d165)

- [x] 20.  https://www.macktrucks.com.mx/trucks/granite-series/    videos are not playing instead error page is shown.
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/0e98ef53-68b9-471f-bde1-48c5998eca93">

- [x] 21.   On page https://www.macktrucks.com.mx/trucks/granite-series/  >> Click on '[Ver las características interiores ->]' button  >>. It navigates to .com instead of ".com.mx" 
![image](https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/53eb5e03-4cbe-4e8f-b8c1-d9f3958e08f9)

- [x] 22.  On page https://www.macktrucks.com.mx/trucks/granite-series/   >>  Column info block background colour is not as expected:
![image](https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/839c353b-5fc3-4d1b-95fe-f6ea245186a3)

- [x] 23.  On page https://www.macktrucks.com.mx/trucks/granite-series/   >>  Cards container block background colour is not as expected & no buttons authored:
- [x]  24. On page https://www.macktrucks.com.mx/trucks/terrapro-series/   section columns block background colour is not as expected
- [x]  25. On page https://www.macktrucks.com.mx/trucks/terrapro-series/   CTA cards button when clicked, navigates user to **.com** request a quote page instead of  **.com.mx** request a quote page
- [x] 26. **HOMEPAGE** :  Footer truck list block is not displayed 
<img width="1784" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-mx/assets/125972657/c0de19da-2262-42ea-b8de-31389b310eca">

**Comment by jonatan-lledo-netcentric** [comment]
8 is fixed, sorry, my bad

**Comment by jonatan-lledo-netcentric** [comment]
- 3: the _Mas información_ button is displayed on hover in the _tren motriz_ secction under _camiones_ dropdown header section
- 4: I added the most important ones except for the login. this link will be out until new news
- 5: the "white" space was for the explore section, but, because there even missing in the legacy page, I removed the section metadata to remove this blank
- 7 Missing section metadata with dark-background, added and fixed
- 9 Added the TM icon
except for the missing page/s, all is fixed @girishdigrajkar

**Comment by girishdigrajkar** [comment]
Revalidated based on above comments and marked done to fixed issues... 
Please see outstanding issues 3, 10, 11
@jonatan-lledo-netcentric @Kannan-CM

**Comment by jonatan-lledo-netcentric** [comment]
buy-mack and mack-news index pages are missing. Please @Kannan-CM , can you add them? thanks

**Comment by Gonzalo-CG** [comment]
Some missing pages that are linked on the nav:

- https://www.macktrucks.com.mx/parts-and-services/support/warranty/
- https://www.macktrucks.com.mx/parts-and-services/support/faqs/
- https://www.macktrucks.com.mx/parts-and-services/support/manuals-and-resources/
- https://www.macktrucks.com.mx/magazine/
- https://www.macktrucks.com.mx/magazine/bulldog-magazine

FYI @Kannan-CM @girishdigrajkar

**Comment by Gonzalo-CG** [comment]
Translation issues:

- [ ] ```Culturista``` is a literal translation of ```Body Builder``` in the sense of "a strong person that lifts weights". Maybe ```Configurador```or ```Configurador de carrocería```could be used.
<img width="720" alt="Screenshot 2023-12-12 at 10 28 12" src="https://github.com/hlxsites/vg-macktrucks-com-mx/assets/139977780/aee68af1-ac96-4d9d-ac32-2da027c680c6">

**Comment by jonatan-lledo-netcentric** [comment]
for button "Mas información" in item 3 could go to this [link](https://www.macktrucks.com/contests/nascarsalutescontest/) in the .com version (or a one translated version). WDYT @Kannan-CM Varun?

**Comment by jonatan-lledo-netcentric** [comment]
10, now is there (the mp4 video share the same issue as other markets, like CA) [link](https://www.macktrucks.com.mx/buy-mack/)

**Comment by jonatan-lledo-netcentric** [comment]
11. will change after the redesign phase, so no actions to take there yet
12. It needs to be updated in code because the 404 page is not reachable by an author. is a developer-only, and it has to be asked to Wendy if it matters, or not
13. The Contact Us page is now live, but the Mack news folder is still missing. @Kannan-CM please, take care of that if any action has to be taken. Thanks.
14. The footer form is now live.
15. buy-mack & request-a-quote are now live. I removed the events link because is US events only
>Repuestos y servicios >> REPUESTOS >> :
[PartsASIST](https://www.macktrucks.com.mx/parts-and-services/parts/partsasist/)

> Repuestos y servicios>> SOPORTE >> :
[Preguntas frecuentes](https://www.macktrucks.com.mx/parts-and-services/support/faqs/)
[Manuales y recursos](https://www.macktrucks.com.mx/parts-and-services/support/manuals-and-resources/)
[Garantía](https://www.macktrucks.com.mx/parts-and-services/support/warranty/)

all of the quoted above are fixed

16 & 17. Hero image and text are already there now
18. Text fixed and added the Registered icon too
19. now has a sub-nav
20. Videos still need a fix to fix the 404 bug
21. fixed, now go to the .com.mx
22, 23 & 24 background fixed
25. CTA buttons currently go to the correct domain
26. explore trucks list added to the footer

**Comment by ZoeBeykirch** [comment]
Remaining issues are content related and can be moved to a teams ticket for CMS and Mack Export team to address.
