### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-mx#2]
This is part of the GoLive activities.

Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

**Comment by manuel-vara** [comment]
GTM Mexico code: GTM-5DKKVHFL

**Comment by jonatan-lledo-netcentric** [comment]
oneTrust id?
is hotjar needed? if so, id?
is fb pixel needed? if so, id?
please @Kannan-CM can you add a comment with the IDs? thanks

**Comment by manuel-vara** [comment]
OneTrust Script for MX:
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js" type="text/javascript" charset="UTF-8" data-domain-script="fec1940d-41f3-40b6-9d96-938da1135d85" ></script> <script type="text/javascript"> function OptanonWrapper() { } </script>
