### ISSUE TITLE
Bug: LA Configurator Link Sharing Issue

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com-mx#23]
### Issue Type

Bug

### Summary

We need to resolve the issue with the missing truck-configurator.json file and ensure that the links in both the follow-up email and the shareable link function correctly. The solution should be applied to all Latin American configurators markets in addition to Mexico. Identified as CORS issue.

### Priority

Blocker

### Description

When users submit their [Anthem](https://www.macktrucks.com.mx/trucks/anthem/build/#/anthem) or [Granite ](https://www.macktrucks.com.mx/trucks/granite-series/build/#/granite) truck configurator builds, the follow-up email they receive contains a broken link to their configured truck. Additionally, when users attempt to click on the copy link to share their build, they encounter the same issue.

Both links appear to include "undefined," in the URL string which seems to be caused by an issue with the truck-configurator.json file. Although this file is linked in the head section, it is currently inaccessible. This JSON file is crucial as it contains the relative links to all configurator pages, which are necessary for constructing the links correctly. The solution should be applied to all Latin American configurators markets in addition to Mexico.  

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices. 

### Steps to Reproduce

1. Navigate to the [Anthem](https://www.macktrucks.com.mx/trucks/anthem/build/#/anthem) and [Granite ](https://www.macktrucks.com.mx/trucks/granite-series/build/#/granite) builders
2. Go through all of the steps until the final summary page and fill out the form to submit your build. 
3. Also on the summary page try to copy the link to share the build (same issue as below)
4. When you get the email follow up, click on the button to view your build. 
5. Observe how these links bring the user to an error page.

### Expected Results

The user should be directed to the proper URL to show the truck configurator that they just built. This works as expected on the Mack USA site for comparison: https://www.macktrucks.com/trucks/anthem/build/

### Actual Results

![Image](https://github.com/user-attachments/assets/1e16371b-f5b1-48fd-a850-2df227d455df)

![image](https://github.com/user-attachments/assets/21f304f0-3d04-4dbb-818f-83bd5758247c)

![image](https://github.com/user-attachments/assets/183a7066-61a8-42e7-a13d-a1a2a125b041)
![image](https://github.com/user-attachments/assets/b87a601b-2b49-4e70-91e6-b4077ce5e74d)
![image](https://github.com/user-attachments/assets/9a253976-5dd2-48e4-a76f-4e4a8d16a274)

**Comment by alexiscoelho** [comment]
Just tried and worked fine. Lets talk better on the refinement

**Comment by silviulungu** [comment]
By using the netcentric email, i'm not able to receive the confirmation email at the end of the configuration.

**Comment by alexiscoelho** [comment]
FYI,
This issue is simply fixed by content.
The truck-configurator url metadata needs to be configured like:
/truck-configurator.json
instead of
https://www.macktrucks.com.ar/truck-configurator.json

**Comment by ZoeBeykirch** [comment]
@Kannan-CM Hey Kannan please see above to ensure the rest of the export sites are configured this way. Thanks in advance!
