### ISSUE TITLE
Bug: Mack Mexico site is not loading any content 

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-macktrucks-com-mx#24]
### Issue Type

Bug

### Summary

Mack Mexico website is down, nothing loads just a white screen. 

### Priority

Blocker

### Description

The https://www.macktrucks.com.mx/ doesn't load, the user only sees a blank screen. 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

Chrome, Safari and Edge have been tested on desktop and iPhone all with the same result. 

### Steps to Reproduce

1. Navigate to https://www.macktrucks.com.mx/
2. view the blank screen and how nothing loads. 

### Expected Results

Website should load content 

### Actual Results

Nothing loads

### Attachment

![image (12)](https://github.com/user-attachments/assets/ba7d9831-9b66-4572-9e0e-e52aa3a0d301)

![image (13)](https://github.com/user-attachments/assets/8242b2c4-0e76-4509-896e-19b484445d8f)

**Comment by BeckyMedlin** [comment]
@alexiscoelho Per @dkuntze, We have to sort out the cdn purge when we make the change to the new urls

**Comment by alexiscoelho** [comment]
That is nothing I/we can do. As far as I know needs to be sorted by Adobe.
@dkuntze told me that he will consult with the cdn crew and see if he can purge everything next time

**Comment by ZoeBeykirch** [comment]
Closed as Darin has resolved this
