### ISSUE TITLE
Spillover - Testing: Site testing for MackTrucks MX (QA & UAT)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-mx#7]
Testing in full all pages/sections of the site.
This issue is for both QA testing and UAT.

**Comment by girishdigrajkar** [comment]
Testing is not fully completed 
Issues logged so far: https://github.com/hlxsites/vg-macktrucks-com-mx/issues/14

**Comment by shirin27** [comment]
As discussed with Becky, the testing tickets are out of scope for the Netcentric team and will be assigned to CMS team.

**Comment by BeckyMedlin** [comment]
Per @Kannan-CM this work is completed.
