### ISSUE TITLE
GoLive Activities Checklist - MackTrucks MX

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-com-mx#8]
Checklist of all activities needed for the GoLive of VolvoTrucks MX:

**Preparation tasks**
- [x] #1 

**Pre, during, and post-GoLive:**
- [x] #7 

**Pre-GoLive:**
- [x] #6 
- [x] #5 
- [x] #4 
- [x] #3 
- [x] #2 
- [x] [AEM GoLive steps](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- Legacy redirects
- Favicon
- CDN configuration
- Update production host

**Post-GoLive:**
- [x] [AEM Post-GoLive Validation](https://www.aem.live/docs/go-live-checklist):
- Performance validation
- 404 Report

**Comment by Kannan-CM** [comment]
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Cookie Settings</button>
